name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: Installer.sln
  BUILD_CONFIGURATION: Release
  PLATFORM: Win32

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Bootstrap vcpkg
      run: .\vpkg\bootstrap-vcpkg.bat

    - name: Build project with MSBuild and vcpkg
      run: |
        msbuild ${{ env.SOLUTION_FILE_PATH }} `
          /p:Configuration=${{ env.BUILD_CONFIGURATION }} `
          /p:Platform=${{ env.PLATFORM }} `
          /p:VcpkgManifestDir=${{ github.workspace }} `
          /p:VcpkgTriplet=x86-windows `
          /p:VcpkgToolchain="${{ github.workspace }}\vpkg\scripts\buildsystems\vcpkg.cmake"
